version: 2
updates:
  # フロントのパッケージ
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '11:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    reviewers:
      - yoshikikomoriya
    assignees:
      - yoshikikomoriya
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # バックエンド（APIサーバー）のパッケージ
  - package-ecosystem: npm
    directory: '/api'
    schedule:
      interval: weekly
      time: '11:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    reviewers:
      - yoshikikomoriya
    assignees:
      - yoshikikomoriya
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # モックサーバーのパッケージ
  - package-ecosystem: npm
    directory: '/mock'
    schedule:
      interval: monthly
      time: '11:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    reviewers:
      - yoshikikomoriya
    assignees:
      - yoshikikomoriya
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '11:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    reviewers:
      - yoshikikomoriya
    assignees:
      - yoshikikomoriya
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
