root: true
extends:
  - eslint:recommended
  - plugin:nuxt/recommended
  - '@nuxtjs/eslint-config-typescript'
  - plugin:prettier/recommended
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
plugins:
  - prettier
  - import # eslint-plugin-importを用いて、モジュールのimport順を制御する
rules:
  import/no-unresolved: off # importの絶対パスの強制を無効化
overrides:
  - files:
      - src/pages/**/*.vue
      - src/layouts/**/*.vue
    rules:
      vue/multi-word-component-names: off # Nuxtの設定とVueスタイルガイドのルールで競合が発生するため、該当のディレクトリ配下でルールを無効にする
